Fix preset config files.
tari-project/tari pull request #2397
Opened 2020-10-27 15:33 UTC by hansieodendaal

## Description
Updated the preset config files:
- Example config
- Windows config

## Motivation and Context
Some information was outdated in these files and a large portion of the example file was deleted recently by accident.

## How Has This Been Tested?
Tested by starting a base node in Windows

## Types of changes

* [X] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [X] Documentation

## Checklist:

* [X] I'm merging against the `development` branch.
* [X] I ran `cargo-fmt --all` before pushing.
* [X] I ran `cargo test` successfully before submitting my PR.
* [X] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

2020-10-28 15:21 UTC, SWvheerden requested changes
Except for the tor transport option this looks fine. 
I left comments. The previous PR on the toml files had a goal of reducing the config. This reverts most of that. 

There is also another 3rd config file that is now mis matched to these two. 
All 3 config files should match or they should be removed to only 2. Currently the options between the two dont matchas well.

2020-10-28 15:21 UTC, SWvheerden commented on common/config/tari_config_sample.toml
> -transport = "tor"
Why is the default tor removed

2020-10-28 15:21 UTC, SWvheerden commented on common/config/tari_config_sample.toml
> -grpc_wallet_address = "127.0.0.1:18143"
I think this needs to be in.

2020-10-28 15:21 UTC, SWvheerden commented on common/config/tari_config_sample.toml
> +
Does this even work?
There is no testnet network.

2020-10-28 15:21 UTC, SWvheerden commented on common/config/tari_config_sample.toml
> +########################################################################################################################
We can remove this.  As Mainnet panics.

2020-10-28 15:21 UTC, SWvheerden commented on common/config/tari_config_sample.toml
> +
We can remove hence mainnet config.

2020-11-02 07:00 UTC, hansieodendaal commented on common/config/tari_config_sample.toml
> -transport = "tor"
It is still in the file not removed, just in the proper place. See line 222

2020-11-02 07:02 UTC, hansieodendaal commented on common/config/tari_config_sample.toml
> -grpc_wallet_address = "127.0.0.1:18143"
Yes, it is still in. See lines 194, 197 & 200.

2020-11-02 07:03 UTC, hansieodendaal commented on common/config/tari_config_sample.toml
> +
Good pickup! Yes, changed.

2020-11-02 07:04 UTC, hansieodendaal commented on common/config/tari_config_sample.toml
> +########################################################################################################################
Agreed, removed

2020-11-02 07:05 UTC, hansieodendaal commented on common/config/tari_config_sample.toml
> +
Agreed, removed

2020-11-02 11:33 UTC, mikethetike approved these changes
I think we need to consolidate our approach to config files. Until then, this can go in as is

2020-11-02 11:39 UTC, merged