WIP: Add consistent install tarballs & startup scripts
tari-project/tari pull request #2490
Opened 2020-12-09 22:15 UTC by hansieodendaal

## Description
This PR adds startup scripts for OSX and Ubuntu, similar to Windows, which are consistent with the updated runtime directory layout. It also adds 3rd party installation script for XMRig that will always install the latest version. Lastly installation tarball setup
scripts will prepare a new zipped tarball for release, also according to the updated directory structure. Installed artefacts will now be similar accross OSX, Ubuntu and Windows. 

## Motivation and Context

## How Has This Been Tested?

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [ ] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

2020-12-10 12:41 UTC, delta1 requested changes

2020-12-10 12:41 UTC, delta1 commented on README.md
>  brew install cmake openssl tor ncurses
testing now, macos `readlink` is BSD version, so add coreutils and change to `greadlink` 

`brew install cmake openssl tor ncurses coreutils`

2020-12-10 12:41 UTC, delta1 commented on buildtools/create_osx_install_zip.sh
> +
```zsh
cp: /Users/byron/code/tari/buildtools/get_xmrig_osx.ps1: No such file or directory
cp: /Users/byron/code/tari/buildtools/install_powershell_osx.sh: No such file or directory
```

2020-12-10 12:41 UTC, delta1 commented on buildtools/create_osx_install_zip.sh
> +
those 2 osx scripts are missing?

2020-12-10 12:49 UTC, delta1 commented
https://github.com/hansieodendaal/tari/pull/1

2020-12-10 12:50 UTC, delta1 commented on README.md
>  brew install cmake openssl tor ncurses
`brew install cmake openssl tor ncurses coreutils`

2021-01-06 17:46 UTC, delta1 commented
Will test again first thing tomorrow 👍

2021-01-08 08:38 UTC, delta1 requested changes
Happy to approve (for macos) once hansieodendaal#2 is included

2021-01-08 08:45 UTC, hansieodendaal commented
Thanks @delta1, will squash all commits now.

2021-01-08 09:33 UTC, delta1 approved these changes
LGTM

2021-01-11 09:12 UTC, merged