Application: mining node
tari-project/tari pull request #2513
Opened 2021-01-06 11:00 UTC by dunnock

## Description
This PR adds mining node application. Mining node has minimum dependency on tari libraries as to make it good example for portability (so far it is still dependent on tari_core BlockHeader and ProofOfWork math), further decoupling might be implemented in follow up PRs. To get the data necessary for mining node requires grpc connection to tari base node and console wallet.

Mining is performed via stages:
1. Validate if base node is bootstrapped
2. Retrieve block template from base node
3. Retrieve coinbase from console wallet
4. Retrieve new block from base node based on template enriched with coinbase output and kernel
5. Mine for block with matching difficulty
6. Submit mined block to base node and restart from 1

When started locally mining node will try to get settings from `[mining_node]` section, including `base_node_grpc_address` and `wallet_grpc_address`. If grpc addresses not set it will try to load from relevant sections from a global config, so when both wallet and node are runnign locally it can start with zero-configuration. By default if `num_mining_threads` setting is not set it will use number of logical CPU cores. It also supports network section overrides.

In addition PR also fixes ConfigLoader trait to use `network` setting (it was still using `use_network` which I think was changed some time ago). Also changes some usize numbers wrapping for current CpuMiner implementation to rust native.

## Motivation and Context
This application would give example of how to write a miner node for tari, which might spike more opensource miners implementation.

## How Has This Been Tested?
I have run mining node in local network with 2 nodes, one of nodes was mining too. Fixed tests for config changes for config loaders.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [X] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [X] I'm merging against the `development` branch.
* [X] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [ ] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

2021-01-06 17:45 UTC, delta1 requested changes
Looking good @dunnock ! 

A few things, I know this is wip: 

- new files need the copyright/licence preamble at the top 
- tari_mining_node crate needs a readme with some instructions 
- maybe `use log::*` to bring log functions into scope instead of having to them all fully qualified 
- config options should be listed in the config samples as well (eg: windows.toml) 

I'm still trying to get things working enough to actually test the mining! But that's due to network and node syncing issues 

Personally I think that the crate could be named `tari_miner` - what do you think @mikethetike ?

2021-01-06 17:45 UTC, delta1 commented on applications/tari_app_utilities/src/initialization.rs
> +use crate::utilities::ExitCodes;
new files should have the copyright preamble I think

2021-01-06 17:45 UTC, delta1 commented on applications/tari_mining_node/src/config.rs
> +//! Miner specific configuration
copyright

2021-01-06 17:45 UTC, delta1 commented on applications/tari_mining_node/src/difficulty.rs
> +use sha3::{Digest, Sha3_256};
copyright

2021-01-07 12:46 UTC, dunnock commented
Thank you for feedback @delta1 , added copyrights, README and config examples. Also imported `log::` stuff. Retained from renaming until Mike would confirm.

2021-01-07 12:48 UTC, dunnock commented
I'm also waiting for https://github.com/tari-project/tari/pull/2514 to land to accomodare grpc changes in this PR.

2021-01-08 15:18 UTC, mikethetike reviewed
Looks good, will test locally

2021-01-08 16:48 UTC, merged