Fix console wallet menu spacing
tari-project/tari pull request #2839
Opened 2021-04-09 12:21 UTC by hansieodendaal

## Description
- Fixed instruction message being cut off when there are pending transactions.
- Improved menu visual effect by adding an additional space before the action (_as per previous unimplemented @delta1  comment_).

With pending transactions:
![image](https://user-images.githubusercontent.com/39146854/114178824-826aee00-993e-11eb-85b6-bc09564fe2de.png)

Without pending transactions:
![image](https://user-images.githubusercontent.com/39146854/114178805-7c750d00-993e-11eb-81ac-80e6817ad4ba.png)

## Motivation and Context
See above.

## How Has This Been Tested?
Running the console wallet.

## Types of changes

* [X] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [ ] New Tests
* [ ] Documentation

## Checklist:

* [X] I'm merging against the `development` branch.
* [X] I ran `cargo-fmt --all` before pushing.
* [ ] I ran `cargo test` successfully before submitting my PR.
* [X] I have squashed my commits into a single commit.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

2021-04-09 12:30 UTC, delta1 requested changes
Looks good, just a syntax error

2021-04-09 12:30 UTC, delta1 commented on applications/tari_console_wallet/src/ui/components/menu.rs
> +        f.render_widget(paragraph2, columns[1]).;
👀

2021-04-12 04:35 UTC, hansieodendaal commented on applications/tari_console_wallet/src/ui/components/menu.rs
> +        f.render_widget(paragraph2, columns[1]).;
Oeps... definitely a finger fault

2021-04-12 04:35 UTC, hansieodendaal commented
> Looks good, just a syntax error

Thank you for the review!

2021-04-12 08:21 UTC, StriderDM approved these changes
LGTM

2021-04-13 06:54 UTC, merged