Fix wallet recovery
tari-project/tari pull request #2896
Opened 2021-05-06 08:20 UTC by SWvheerden

## Description

Wallet recovery atm in time can only recover non coinbase outputs. This PR fixes the coinbase UTXO importing. This will allow the wallet to recover coinbase UTXOs.

## Motivation and Context

## How Has This Been Tested?

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I have squashed my commits into a single commit.

2021-05-06 12:16 UTC, hansieodendaal approved these changes
LGTM

*Nit:* Maybe we need a unit test that also test importing UTXOs with non-default features?

2021-05-07 09:33 UTC, mikethetike commented on base_layer/wallet/src/output_manager_service/service.rs
> +            trace!(
This could be `info` or `debug` even

2021-05-07 09:33 UTC, mikethetike approved these changes

2021-05-07 10:43 UTC, delta1 requested changes
There's a test for `import_utxo` in `base_layer/wallet/tests/wallet/mod.rs` which should be updated to cover this change.

2021-05-07 11:09 UTC, SWvheerden commented
That test, would not catch the problem. I am updating PR  #2872  to include these changes as they have changed

2021-05-11 12:11 UTC, merged