[DO NOT MERGE] test: cucumber forced sync
tari-project/tari pull request #3230
Opened 2021-08-23 09:36 UTC by Cifko

## Description
Add cucumber test that tests forced sync to single node.

## How Has This Been Tested?
npm test -- --name "Force sync many nodes agains one peer"

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I have squashed my commits into a single commit.

2021-08-23 09:39 UTC, Cifko commented
The problem is that syncing 1000 nodes is not working. 999 works fine. Do we forbid sync over 1000 blocks (I don't think so). Haven't look at the error yet.
There are two options right now
1) set it to 999 blocks, create new ticket for the 1k sync and change it later to 1k
2) leave it at 1k and investigate now

2021-08-24 08:31 UTC, delta1 requested changes
Looking good, just a typo. Testing locally now.

2021-08-24 08:31 UTC, delta1 commented on integration_tests/features/Sync.feature
> +  Scenario Outline: Force sync many nodes agains one peer
```suggestion
  Scenario Outline: Force sync many nodes against one peer
```

2021-08-24 09:05 UTC, delta1 submitted a review, later dismissed
Works well!

2021-08-24 09:51 UTC, philipr-za commented
> The problem is that syncing 1000 nodes is not working. 999 works fine. Do we forbid sync over 1000 blocks (I don't think so). Haven't look at the error yet.
> There are two options right now
> 
>     1. set it to 999 blocks, create new ticket for the 1k sync and change it later to 1k
> 
>     2. leave it at 1k and investigate now

I believe this must be a bug related to the pruning horizon which is by default 1000 blocks?

2021-08-26 14:36 UTC, stringhandler approved these changes

2021-08-26 16:48 UTC, merged