feat: show status avx2 feature and randomx count and flags
tari-project/tari pull request #3261
Opened 2021-08-30 06:40 UTC by Cifko

Description
---
- Add new info into wallet:
  - Avx2 enabled/disabled status.
- Add new info into base node
  - Avxs2 enabled/disabled
  - number of randomx vm, and flags

2021-08-30 10:31 UTC, delta1 requested changes
Looks good, you just have some clippy issues with unneeded return statements

2021-08-30 11:10 UTC, mikethetike submitted a review, later dismissed

2021-09-03 10:19 UTC, Cifko commented
> Looks good, you just have some clippy issues with unneeded return statements

Fixed, merge to up-to-date dev branch (some merge issues), clippy is good.

2021-09-03 10:50 UTC, mikethetike approved these changes

2021-09-06 18:40 UTC, merged