feat: add unique id index to lmdb
tari-project/tari pull request #3407
Opened 2021-10-04 06:56 UTC by StriderDM

Description
---
Adds unique_id index to lmdb

2021-10-04 09:15 UTC, sdbondi reviewed
utAck - so the idea is that the hash preimage is `asset namespace/class || the token`?

2021-10-04 09:15 UTC, sdbondi commented on base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
> +        if let Some(unique_id) = &output.features.unique_id.clone() {
```suggestion
        if let Some(unique_id) = output.features.unique_id.as_ref() {
```

2021-10-04 09:15 UTC, sdbondi commented on base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
> +        if let Some(unique_id) = input.features.unique_id.clone() {
```suggestion
        if let Some(unique_id) = input.features.unique_id.as_ref() {
```

2021-10-04 09:15 UTC, sdbondi commented on base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
> +                if let Some(unique_id) = output.features.unique_id.clone() {
```suggestion
                if let Some(unique_id) = output.features.unique_id.as_ref() {
```

2021-10-04 09:29 UTC, delta1 commented
> utAck - so the idea is that the hash preimage is `asset namespace/class || the token`?

Sounds right, I think according to [1] `(parent_pub_key, unique_id)` should be unique 

[1]: https://github.com/tari-project/tari/pull/3340/files#diff-62c91e11620b9f0105f0c6418dbce59c6924086076081011ef45d38d61c05617R82

2021-10-04 09:40 UTC, delta1 requested changes
as per the [proposed RFC](https://github.com/tari-project/tari/pull/3407#issuecomment-933309055) the key for the index should be `parent_public_key || unique_id`

2021-10-04 09:45 UTC, delta1 commented
I'm happy to pick this up as part of the validations I'm doing @StriderDM 👍

2021-10-05 11:36 UTC, delta1 commented
Included in #3416 thanks @StriderDM !

2021-10-05 11:36 UTC, closed without merging