fix: add display_currency_decimal method
tari-project/tari pull request #3445
Opened 2021-10-11 14:48 UTC by therustmonk

Description
---
The inner type of `Tari` changed from `f64` to `decimal_rs::Decimal`.
Also, `display_currency` method was replaced with `format_currency` that adds separators to formatted strings.

Motivation and Context
---
`display_currency` method forces us to use `f64` that is not accurate for finance calculations.

How Has This Been Tested?
---
Updated unit tests.
**TODO:** Smoke test: run the wallet and the node.

2021-10-12 07:26 UTC, therustmonk commented
The `experiment` commit contains `Trai(Decimal)` type.
It still uses `f64` all around, but we can replace it with Decimals. It should work.

Or how about removing `Tart(f64)` completely and use `MiniTari` everywhere with some special formatting methods?

2021-10-13 13:46 UTC, therustmonk commented on base_layer/core/src/transactions/tari_amount.rs
> +#[derive(
`newtype-ops` looks unmaintained. How about using `derive_more` instead?

2021-10-13 13:54 UTC, therustmonk commented
It's also possible to remove `Tari` type completely and use `MicroTari` with a special formatted like this:

```rust
pub struct TariFormat {
    MicroTari,
    Tari,
    Auto,
}

pub struct FormattedTari {
    format: TariFormat,
    separator: Option<char>,
}

impl MicroTari {
    pub fn formatted(&self, format: TariFormat, separator: Option<char>) -> FormattedTari {
        FormattedTari {
            format,
            separator,
        }
    }
}

impl Display for FormattedTari { /* etc. */ }
```

What do you think?

2021-10-13 14:35 UTC, delta1 requested changes
Looking good, just a few small things

2021-10-13 14:35 UTC, delta1 commented on applications/tari_console_wallet/src/automation/error.rs
> +    TariConvertError(#[from] TariConvertError),
```suggestion
    #[error("Tari value conversion error `{0}`")]
    TariConversionError(#[from] TariConversionError),
```

2021-10-13 14:35 UTC, delta1 commented on base_layer/core/src/transactions/tari_amount.rs
> +                        // TODO: Check. It can't be `NaN` anymore. Still we need `.max(0.0)` check?
is this comment still current?

2021-10-13 14:35 UTC, delta1 commented on base_layer/core/src/transactions/tari_amount.rs
> +        MicroTari((v.0 * 1_000_000u32).try_into().unwrap())
unwrap?

2021-10-13 14:35 UTC, delta1 commented on base_layer/core/src/transactions/tari_amount.rs
> +#[derive(
Yeah if we're already using `derive_more` now and it's easy to remove `newtype_ops` I think that's fine

2021-10-13 14:35 UTC, delta1 commented on base_layer/core/src/transactions/tari_amount.rs
> +pub type TariConvertError = DecimalConvertError;
```suggestion
pub type TariConversionError = DecimalConvertError;
```

2021-10-14 06:52 UTC, therustmonk commented on base_layer/core/src/transactions/tari_amount.rs
> +                        // TODO: Check. It can't be `NaN` anymore. Still we need `.max(0.0)` check?
No idea, why we compare the unsigned value with `0.0` 🤷‍♂️ I left the comment to double-check it together. How about removing that `max` call?

2021-10-14 06:59 UTC, therustmonk commented on base_layer/core/src/transactions/tari_amount.rs
> +        MicroTari((v.0 * 1_000_000u32).try_into().unwrap())
In the past, the value could be truncated silently, I thought it's better to panic here, but probably even better to replace the trait to `TryFrom`.

2021-10-14 07:12 UTC, delta1 commented on base_layer/core/src/transactions/tari_amount.rs
> +                        // TODO: Check. It can't be `NaN` anymore. Still we need `.max(0.0)` check?
It looks like you did remove the max? Which is why I ask :) 

![image](https://user-images.githubusercontent.com/351403/137269013-1b52bd4e-64ee-45e8-8e44-eb5b6ce64a7a.png)

2021-10-14 07:30 UTC, therustmonk commented on base_layer/core/src/transactions/tari_amount.rs
> +                        // TODO: Check. It can't be `NaN` anymore. Still we need `.max(0.0)` check?
Ah, right, it's another one. I've removed it, because if a value is not less than 0.0 (greater or equal 0.0) it's always a win in `max(0.0)` comparison. I guess we had it to handle the `f64::NaN` case, but `Decimal` doesn't support `NaN` values at all and that comparison doesn't make sense anymore. If I'm correct about why we had that `max(0.0)` call.

2021-10-14 07:31 UTC, therustmonk commented on base_layer/core/src/transactions/tari_amount.rs
> +                        // TODO: Check. It can't be `NaN` anymore. Still we need `.max(0.0)` check?
https://docs.rs/decimal-rs/0.1.20/src/decimal_rs/parse.rs.html#266
https://docs.rs/decimal-rs/0.1.20/src/decimal_rs/parse.rs.html#321

2021-10-14 16:22 UTC, stringhandler approved these changes
Would have preferred to remove this function completely, but this is an improvement

2021-10-14 16:55 UTC, merged