feat(wallet_ffi)!: add get_balance callback to wallet ffi
tari-project/tari pull request #3475
Opened 2021-10-19 10:43 UTC by hansieodendaal

Description
---
- Added get_balance callback to the wallet ffi callback handler that fires only if the balance has actually changed.
- Expanded the wallet ffi callback handler test framework to include a mock output manager request-response server.
- _**Update:** Added required methods and interfaces to the cucumber test framework._
- _**Update:** Fixed flaky wallet FFI cucumber tests._
- _**Update:** Fixed a bug in the wallet FFI cucumber test framework where the return type of `ref.types.ulonglong` did not correspond to the Rust return type and had a memory alignment problem._
- _**Update:** Fixed an issue whereby on a fast 8-core multi-tasking computer (e.g. AMD Ryzen 7 2700X) some of the wallet FFI cucumber tests did not complete properly after the test and went into an endless wait. The root cause of this issue has been traced down to incorrect use of synchronous calls to wallet FFI destroy methods where in actual fact those methods have async behaviour._
- _**Update:** Re-applied #3271._

~~The following anomaly exists when compiling the proposed `wallet_ffi/tests` module:~~
```
24 | use tari_wallet_ffi::callback_handler::CallbackHandler;
   |     ^^^^^^^^^^^^^^^ use of undeclared crate or module `tari_wallet_ffi`
```

_**Update**_ ~~Various code organizations have been tried, all with the same result. As an alternative, a working test and output manager service mock has been added into the test module in `callback_handler.rs`. Hopefully, the anomaly can be fixed. Duplicate code will be removed before the final commit.~~

Motivation and Context
---
- Mobile wallet efficiency.
- Resilient wallet FFI cucumber tests.

How Has This Been Tested?
---
- Expanded the current FFI `test_callback_handler` unit test.
- _**Update:** Ran all the wallet FFI cucumber tests to verify the new callback is working properly when using the wallet FFI library:_ 

```
2021-10-21T06:29:32.160Z callbackTransactionValidationComplete(9123501482775375388,0)
2021-10-21T06:29:32.161Z callbackBalanceUpdated: available = 0,  time locked = 0  pending incoming = 2000000 pending outgoing = 0
2021-10-21T06:29:32.263Z received Transaction with txID 14659183447022727953

...

2021-10-21T06:31:38.358Z Transaction with txID 14659183447022727953 was mined.
2021-10-21T06:31:38.358Z callbackBalanceUpdated: available = 2000000,  time locked = 2000000  pending incoming = 0 pending outgoing = 0
2021-10-21T06:31:38.359Z callbackTransactionValidationComplete(17755253868227079780,0)
```

2021-10-19 11:51 UTC, philipr-za reviewed
So you don't actually need the mod.rs in the test module. Check out [Rust Test Organization ](https://doc.rust-lang.org/book/ch11-03-test-organization.html).

In terms of the test module accessing the crate the problem is caused by:
```
[lib]
crate-type = ["staticlib","cdylib"]
``` 
In the cargo.toml. https://github.com/rust-lang/cargo/issues/6659 mentioned adding "lib" to that list fixes it and I checked it does.

2021-10-19 13:48 UTC, StriderDM commented on base_layer/wallet_ffi/wallet.h
> +                                 void (*callback_balance_updated)(struct TariBalance *),
You need a forward declaration of `struct TariBalance;` in this file or it will result in a linker error in the application trying to link against this.

Additionally:
You will need a method to free the memory for this struct.
Methods to retrieve the values for this struct as simple C types which can safely cross the FFI boundary.
Methods to set the values for fields within this struct (appears to be optional here).
Method to allocate memory for this struct (appears to be optional here).

2021-10-19 14:11 UTC, StriderDM commented on base_layer/wallet_ffi/Cargo.toml
> +crate-type = ["staticlib","cdylib", "lib"]
I think this will have unintended consequences.

Looks like the cause of the problem is some tests are missing:
```
#[cfg(test)]
mod test {
...
}
```

2021-10-19 15:32 UTC, philipr-za commented on base_layer/wallet_ffi/Cargo.toml
> +crate-type = ["staticlib","cdylib", "lib"]
I think when the duplication of the tests is resolved that will no longer be an issue. The thing I am worried about is whether adding that flag affects the libWallet build at all. @StriderDM would you mind just adding the "lib" flag to the current Dev branch and see if the build goes ok, please?

2021-10-20 06:41 UTC, philipr-za commented on base_layer/wallet_ffi/wallet.h
> +                                 void (*callback_balance_updated)(struct TariBalance *),
Don't need to be able to set the members of the struct or allocate memory as its only every provided by the backend. So just need to be able retrieve the members and free the memory.

This is worth doing because I see at the moment you have to make a separate DB call for each member of the balance instead of a single db call and destructuring that result.

2021-10-20 11:45 UTC, hansieodendaal commented on base_layer/wallet_ffi/Cargo.toml
> +crate-type = ["staticlib","cdylib", "lib"]
After discussion with @StriderDM I decided to do away with adding `"lib"` to `crate-type` to enable the separate `tests` folder and to use the internal `#[cfg(test)] mod test {...` option. I propose investigating and repackaging tests could be a separate PR if needed.

2021-10-20 19:59 UTC, StriderDM commented
Nicely done @hansieodendaal. Well done. Just needs a format and the integration test should run, approved otherwise.

2021-10-21 05:37 UTC, hansieodendaal commented
> Nicely done @hansieodendaal. Well done. Just needs a format and the integration test should run, approved otherwise.

Thank you @StriderDM; your inputs were invaluable.

2021-10-21 07:10 UTC, StriderDM submitted a review, later dismissed

2021-10-21 12:12 UTC, philipr-za commented on base_layer/wallet_ffi/src/callback_handler.rs
> +/// This macro unlocks a Mutex or RwLock. If the lock is poisoned (i.e. panic while unlocked) the last value
Not needed

2021-10-21 12:12 UTC, philipr-za commented on base_layer/wallet_ffi/src/callback_handler.rs
> +    balance_cache: Arc<Mutex<Balance>>,
You don't need a mutex here, the callback handler doesn't access this value from different tasks.

2021-10-21 12:12 UTC, philipr-za commented on base_layer/wallet_ffi/Cargo.toml
> +tari_service_framework = { path = "../../base_layer/service_framework" }
This should be a Dev-dependancy as it is only used in tests.

2021-10-21 12:12 UTC, philipr-za commented on base_layer/wallet_ffi/src/lib.rs
> +/// Frees memory for a TariBalance
This should be with the other methods to do with TariBalance

2021-10-21 12:12 UTC, philipr-za commented on integration_tests/features/WalletFFI.feature
> +        And I wait 5 seconds
Why are these needed? Can they be replaces with some sort of condition check? We have been on a long quest to remove these kind of waits in favour of hard condition checks. These kind of waits are where flakiness lie.

2021-10-21 12:12 UTC, philipr-za commented on base_layer/wallet_ffi/src/callback_handler.rs
> +    macro_rules! acquire_lock {
If we cannot put this into the tests folder then at the very least lets put this module in a separate file in this folder.

2021-10-21 13:56 UTC, hansieodendaal commented on integration_tests/features/WalletFFI.feature
> +        And I wait 5 seconds
Removing the waits

2021-10-25 06:17 UTC, philipr-za commented
Clippy says no

2021-10-25 06:43 UTC, hansieodendaal commented
> Clippy says no

Yip, still busy sorting out a flaky test

2021-10-25 08:50 UTC, hansieodendaal commented on integration_tests/features/WalletFFI.feature
> +        And I wait 5 seconds
I believe the tests have now been made more predictive; see the latest commit.

2021-10-25 09:15 UTC, philipr-za submitted a review, later dismissed

2021-10-26 06:44 UTC, stringhandler requested changes

2021-10-26 06:44 UTC, stringhandler commented on base_layer/wallet_ffi/Cargo.toml
> +version = "0.20.0"
Please don't change versions. I need to prep the changelog and this will mess with that process

2021-10-26 07:03 UTC, hansieodendaal commented on base_layer/wallet_ffi/Cargo.toml
> +version = "0.20.0"
Reverted

2021-10-26 07:22 UTC, stringhandler submitted a review, later dismissed

2021-10-27 06:36 UTC, philipr-za submitted a review, later dismissed

2021-10-28 09:46 UTC, philipr-za submitted a review, later dismissed

2021-10-28 18:06 UTC, philipr-za approved these changes

2021-10-28 18:07 UTC, merged