refactor: split sqlitedb file
tari-project/tari pull request #3541
Opened 2021-11-05 09:01 UTC by mikethetike

Splits the sqlitedb file into a mod with individual files to help manage them better. 
This has been done on the validator-node branch so doing this on development will make merges easier

2021-11-05 09:06 UTC, delta1 approved these changes
LGTM

2021-11-05 09:11 UTC, philipr-za approved these changes, later dismissed

2021-11-05 09:22 UTC, delta1 requested changes
Tests need updating

2021-11-10 07:31 UTC, philipr-za approved these changes

2021-11-10 08:08 UTC, merged