feat: add versioning to transaction(input,output,kernel)
tari-project/tari pull request #3709
Opened 2022-01-17 06:56 UTC by Cifko

Description
---
Add versioning to Transactions.

How Has This Been Tested?
---
Some cucumber tests.

2022-01-17 08:51 UTC, hansieodendaal reviewed
Hi there,

Just some comments to consider.

Thanks.

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/output_features.rs
> +}
I think this should go in a separate file

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_input.rs
> +
I think this should go in a separate file

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_kernel.rs
> +}
I think this should go in a separate file

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_output.rs
> +
I think this should go in a separate file

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
> +        println!("{}:{}", file!(), line!());
Was print this perhaps for debugging?

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
> +        println!("{}:{}", file!(), line!());
Print?

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
> +        println!("{}:{}", file!(), line!());
Print?

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
> +        println!("{}:{}", file!(), line!());
Print?

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
> +        println!("{}:{}", file!(), line!());
Print?

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/output_features.rs
> +
I think we need an `OutputFeaturesVersion::GetCurrentVersion()` implementation here.

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/output_features.rs
> +            OutputFeaturesVersion::DIBBLER,
```suggestion
            OutputFeaturesVersion::GetCurrentVersion(),
```

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_input.rs
> +
I think we need a `TransactionInputVersion::GetCurrentVersion()` implementation here.

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_input.rs
> +            TransactionInputVersion::DIBBLER,
```suggestion
            TransactionInputVersion::GetCurrentVersion(),
```

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_input.rs
> +                version: TransactionOutputVersion::DIBBLER,
```suggestion
                version: TransactionOutputVersion::GetCurrentVersion(),
```

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_kernel.rs
> +            TransactionKernelVersion::DIBBLER,
```suggestion
            TransactionKernelVersion::GetCurrentVersion(),
```

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_output.rs
> +            TransactionOutputVersion::DIBBLER,
```suggestion
            TransactionOutputVersion::GetCurrentVersion(),
```

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/unblinded_output.rs
> +            TransactionOutputVersion::DIBBLER,
```suggestion
            TransactionOutputVersion::GetCurrentVersion(),
```

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_kernel.rs
> +
I think we need a `TransactionKernelVersion::GetCurrentVersion()` implementation here.

2022-01-17 08:51 UTC, hansieodendaal commented on base_layer/core/src/transactions/transaction/transaction_output.rs
> +
I think we need a `TransactionOutputVersion::GetCurrentVersion()` implementation here.

2022-01-17 10:26 UTC, sdbondi commented on base_layer/core/src/transactions/transaction/output_features.rs
> +    DIBBLER = 0,
Versions don't correspond with networks. Suggest `V1`, `V2` etc

2022-01-17 10:27 UTC, sdbondi commented on applications/tari_app_grpc/src/conversions/transaction_output.rs
> +            TransactionOutputVersion::try_from(output.version as u8)?,
Should check for u8 overflows
```suggestion
            TransactionOutputVersion::try_from(u8::try_from(output.version).map_err(|_| "Invalid version: overflowed u8"))?,
```

2022-01-17 12:51 UTC, Cifko commented on base_layer/wallet/src/output_manager_service/storage/sqlite_db/mod.rs
> +        println!("{}:{}", file!(), line!());
Forgot some debug ;-)

2022-01-17 16:11 UTC, mikethetike commented on base_layer/core/src/transactions/transaction/output_features_version.rs
> +    V1 = 0,
```suggestion
    V0 = 0,
```

2022-01-17 16:11 UTC, mikethetike commented on base_layer/core/src/transactions/transaction/transaction_input_version.rs
> +    V1 = 0,
```suggestion
    V0 = 0,
```

2022-01-17 16:11 UTC, mikethetike commented on base_layer/core/src/transactions/transaction/transaction_kernel_version.rs
> +    V1 = 0,
```suggestion
    V0 = 0,
```

2022-01-18 06:03 UTC, SWvheerden requested changes
This looks good, but you need to remember to update the genesis block header as well as the MMR has now changed.

2022-01-18 06:03 UTC, SWvheerden commented on base_layer/core/src/blocks/genesis_block.rs
> +        vec![TransactionOutput::new_current_version(
You have changed the hash of the output, you need to update the MMR in the header of the genesis block as well.

2022-01-18 06:03 UTC, SWvheerden commented on base_layer/core/src/transactions/transaction/mod.rs
> +        .chain((version as u8).to_le_bytes())
Look at the comment in the genesis block, you need to update the MMR in the header.

2022-01-18 06:51 UTC, Cifko commented
I've also forgot to add version to the TransactionInput hash. Added that as well. The genesis block is updated.

2022-01-18 08:21 UTC, Cifko commented
Added `Clippy.toml` for the number of arguments (set to 15) and removed the `#[allow(clippy::too_many_arguments)]`. This is only done for the `base_layer/core` crate.

2022-01-18 12:55 UTC, mikethetike approved these changes

2022-01-18 13:13 UTC, merged