fix: prepend message to signing
tari-project/tari pull request #5394
Opened 2023-05-18 13:53 UTC by stringhandler

Description
---
Add a message to prevent arbitrary signing

Motivation and Context
---
This method is exposed via ffi and could allow users to sign transactions or arbitrary data

Breaking Changes
---

- [ ] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [x] Other - If this method was used externally, those methods will break.

2023-05-18 14:04 UTC, AaronFeickert commented
Wasn't this functionality removed in [PR 4891](https://github.com/tari-project/tari/pull/4891) a while back due to a previous unsafe implementation?

2023-05-18 14:22 UTC, AaronFeickert requested changes
This can still technically induce collisions, albeit likely not ones that could lead to things like unintentional transaction signing.

A safer and more comprehensive fix would be to use a signature construction that uses a different domain-separated challenge hasher. Then it's not possible (up to the collision resistance of the hasher) to produce collisions.

2023-05-19 05:50 UTC, SWvheerden approved these changes

2023-05-19 17:40 UTC, AaronFeickert commented
Once completed and tested, [this PR](https://github.com/tari-project/tari/pull/5400) applies domain separation as [referenced above](https://github.com/tari-project/tari/pull/5394#pullrequestreview-1432810894), and supersedes this PR.

2023-05-22 08:25 UTC, SWvheerden commented
replaced by PR: #5400

2023-05-22 08:25 UTC, closed without merging