fix: update libs to fix cargo audit
tari-project/tari pull request #5772
Opened 2023-09-14 13:15 UTC by stringhandler

Description
---
Updates a few crates that are failing cargo audit. 
Notably: trust_dns, clap

Motivation and Context
---
This allows us to remove the exceptions in cargo audit, but also to prevent them from triggering cargo-audit failures downstream, for example in the tari dan project

How Has This Been Tested?
---
clippy and cargo audit

What process can a PR reviewer use to test or verify this change?
---
Run cargo audit manually

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

2023-09-14 13:24 UTC, SWvheerden submitted a review, later dismissed

2023-09-14 17:54 UTC, AaronFeickert requested changes
Looks like several remaining issues that CI caught, and which I also saw locally:
- the `clap` API for `App` has been replaced with `Command`
- the `clap` API for `Arg` has changed
- the `clap` API for `ArgMatches` has changed
- `DnsResponse::from_message` should be used to parse a response
- `env_logger::from_env` is deprecated in favor of `env_logger::Builder::from_env`

2023-09-14 19:09 UTC, AaronFeickert commented
Fixes are available on [this commit](https://github.com/AaronFeickert/tari/commit/3f599e1b2128c9addcec26d110102741c8cc979b).

2023-09-15 17:13 UTC, AaronFeickert requested changes

2023-09-15 17:13 UTC, AaronFeickert commented on applications/minotari_console_wallet/src/cli.rs
> -    #[clap(long, parse(try_from_str=parse_start_time))]
Removing the parser fails testing, as `now` is no longer a valid value. Either the parser should be added back, or the offending tests should be modified accordingly.

2024-04-15 09:44 UTC, closed without merging