fix(tariscript): multisig ordered signatures and pubkeys
tari-project/tari pull request #5961
Opened 2023-11-16 11:14 UTC by brianp

Description
---
Update the multisig op code checks to care about the order of keys and signatures. This is to assist with reducing the amount of iterations and processing a node is required to perform to validate a collection.

Motivation and Context
---
Low/Minor audit issue to reduce processing for nodes.

How Has This Been Tested?
---
Test suite / CI

What process can a PR reviewer use to test or verify this change?
---
Look at the test additions. They make it more clear what the effects of the changes are.

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

2023-11-16 17:40 UTC, AaronFeickert requested changes

2023-11-16 17:40 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
>      /// * Every public key can be used AT MOST once.
```suggestion
    /// * The list may contain duplicate keys, but each occurrence of a public key may be used AT MOST once.
```

2023-11-16 17:40 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
> +    /// * The public keys and signatures must both be ordered.
```suggestion
    /// * The ordering of signatures on the stack MUST match the relative ordering of the corresponding public keys.
```

2023-11-16 17:40 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
>      /// * Every public key can be used AT MOST once.
Should also include a comment that signatures are required to be unique, a case which could legitimately arise on a repeated public key.

2023-11-16 17:40 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
> +                if !sig_set.contains(s) && s.verify_raw_canonical(pk, &message) {
I think you can move `!sig_set.contains(s)` outside of (and immediately prior to) the inner `for` loop to save on hash lookups. This means there is a single check for signature duplication. If the signature is verified and it is added to the hash set, the `break` will short-circuit subsequent lookups anyway in favor of the single check after the loop.

2023-11-16 17:40 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
> +                if !sig_set.contains(s) && s.verify_raw_canonical(pk, &message) {
In fact, I think such a move improves clarity of intent as well. It means you assert that a signature initially hasn't been verified already (or else it's a duplicate and the operation fails), and then assert that the signature is eventually verified (or else the operation fails).

2023-11-16 17:41 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
> +                if !sig_set.contains(s) && s.verify_raw_canonical(pk, &message) {
Tested this change locally, and all tests pass.

2023-11-16 20:07 UTC, AaronFeickert requested changes

2023-11-16 20:07 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
> +                if !sig_set.contains(s) && s.verify_raw_canonical(pk, &message) {
The use of `verify_raw_canonical` means that `message` _must_ safely bind the public key. In this case, it is identical across the full set of allowed public keys, which technically breaks Fiat-Shamir. In practice, it means that a forger would need to target any one of the public keys, the complexity of which depends on the number of public keys in the set.

2023-11-16 21:43 UTC, AaronFeickert commented on infrastructure/tari_script/src/script.rs
> +                if !sig_set.contains(s) && s.verify_raw_canonical(pk, &message) {
See #5817 for a related issue.

2023-11-17 12:31 UTC, SWvheerden approved these changes

2023-11-17 15:08 UTC, merged