refactor: better network global
tari-project/tari pull request #6014
Opened 2023-12-05 12:32 UTC by stringhandler

Description
---
Removes the mutex and allows tests to run in parallel

Motivation and Context
---
Built on #6004 

The previous versions of these test relied on setting the Network globally. If other tests are running at the same time, these tests can fail because the network is switched. I investigated using ThreadLocalStorage and TaskLocalStorage from tokio, but these could result threads having different networks set and it would be hard to confirm that the entire process was using the correct network.

I opted instead to ignore the `set_network` test and add a parameter to the DomainSeparatedHasher to allow a different network to be tested.

How Has This Been Tested?
---
Ran cargo test

What process can a PR reviewer use to test or verify this change?
---
This fixes tests and provides a cleaner interface

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

2023-12-05 13:08 UTC, SWvheerden commented on base_layer/core/src/consensus/consensus_encoding/hashing.rs
> +        //        *CURRENT_NETWORK.lock().unwrap() = Network::Esmeralda;
```suggestion
```

2023-12-05 13:10 UTC, SWvheerden submitted a review, later dismissed
this looks like it could solve the test problem

2023-12-05 16:23 UTC, brianp approved these changes
LGTM

2023-12-05 19:58 UTC, AaronFeickert requested changes

2023-12-05 19:58 UTC, AaronFeickert commented on applications/minotari_app_utilities/src/network_check.rs
> +            // let mut current_network = Network::current();
```suggestion
```

2023-12-05 19:58 UTC, AaronFeickert commented on base_layer/core/src/consensus/consensus_encoding/hashing.rs
> +
```suggestion
```

2023-12-05 19:58 UTC, AaronFeickert commented on base_layer/core/src/consensus/consensus_encoding/hashing.rs
> +        // Network::set_current(Network::MainNet);
```suggestion
```

2023-12-05 19:58 UTC, AaronFeickert commented on base_layer/core/src/consensus/consensus_encoding/hashing.rs
> +
```suggestion
```

2023-12-05 19:58 UTC, AaronFeickert commented on applications/minotari_app_utilities/src/network_check.rs
> +            assert!(set_network_if_choice_valid(network).is_ok());
This fails for me locally on the first trip through the loop. The issue is that `Network::set_current` returns an error.

2023-12-08 11:18 UTC, SWvheerden commented
Closing this for: https://github.com/tari-project/tari/pull/6004

2023-12-08 11:18 UTC, closed without merging