WIP: ledger blind sign
tari-project/tari pull request #6264
Opened 2024-04-10 10:54 UTC by brianp

Description
---
This PR is to share a WIP of the ledger blind sign.

Motivation and Context
---

How Has This Been Tested?
---

What process can a PR reviewer use to test or verify this change?
---

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

2024-05-15 11:30 UTC, SWvheerden reviewed
Looking good, small comments, then we can merge this

2024-05-15 11:30 UTC, SWvheerden commented on applications/minotari_ledger_wallet/wallet/Cargo.toml
> +tari_crypto = { version = "0.20.0", default-features = false, features = ["borsh"]}
```suggestion
tari_crypto = { version = "0.21.0", default-features = false, features = ["borsh"]}
```

2024-05-15 11:30 UTC, SWvheerden commented on base_layer/wallet/tests/transaction_service_tests/storage.rs
>          .await
This should be fixed:
Should be:
```
let script_key_id = KeyId::Derived...
let public_script_key = key_manager.get_public)key(script_key_id)
```

2024-05-15 11:30 UTC, SWvheerden commented on base_layer/wallet/tests/output_manager_service_tests/service.rs
> +            .get_next_key(TransactionKeyManagerBranch::CommitmentMask.get_branch_key())
This should be fixed:
Should be:
```
let script_key_id = KeyId::Derived...
let public_script_key = key_manager.get_public)key(script_key_id)
```

2024-05-15 11:30 UTC, SWvheerden commented on base_layer/key_manager/src/key_manager_service/service.rs
> +                let branch_key = km.get_private_key(*index)?;
FYI:
With the new view key, this will be a problem, so we need to change this somewhat

2024-05-15 11:30 UTC, SWvheerden commented on base_layer/core/tests/tests/node_comms_interface.rs
> +            .get_next_key(TransactionKeyManagerBranch::CommitmentMask.get_branch_key())
This should be fixed:
Should be:
```
let script_key_id = KeyId::Derived...
let public_script_key = key_manager.get_public)key(script_key_id)
```

2024-05-15 13:37 UTC, hansieodendaal requested changes
Looks really good, just some pertinent comments to be addressed in this PR or alternatively new issues to be created to address the comments after this PR is merged please.

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
> +}
We need to ensure that the selected Ledger device is the proper one. A user can have more than one device attached.
```suggestion
pub fn get_transport() -> Result<TransportNativeHID, LedgerDeviceError> {
    let hid = HidApi::new().map_err(|e| LedgerDeviceError::HidApi(e.to_string()))?;
    
    const LEDGER_VID: u16 = 0x2c97;
    const LEDGER_USAGE_PAGE: u16 = 0xFFA0;
    let device_list: Vec<_> = hid
        .device_list()
        .filter(|dev| dev.vendor_id() == LEDGER_VID && dev.usage_page() == LEDGER_USAGE_PAGE)
        .collect();
    let index = if device_list.is_empty() {
        return Err(LedgerDeviceError::NativeTransport("No ledger device found".to_string()));
    } else if device_list.len() > 1 {
        select_ledger(&device_list)
    } else {
        0
    };

    TransportNativeHID::new(&hid).map_err(|e| LedgerDeviceError::NativeTransport(e.to_string()))
}

use dialoguer::{theme::ColorfulTheme, Select};

fn select_ledger(device_list: &[&DeviceInfo]) -> usize {
    println!();
    let binding = ColorfulTheme::default();
    let mut binding = Select::with_theme(&binding);
    let prompt = binding
        .with_prompt("More than one Ledger device detected, which one should be used?")
        .default(0);
    for device in device_list {
        prompt.item(&format!(
            "Device: {}, {}, {:?}",
            device.manufacturer_string().unwrap_or("no manufacturer string"),
            device.product_string().unwrap_or("no product string"),
            device.path()
        ));
    }
    let index = prompt.interact().unwrap();
    println!();
    index
}

```

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_console_wallet/src/init/mod.rs
> +                            let ledger = LedgerWallet::new(account, wallet_config.network, None);
We need to check the ledger app name and version here before we continue:
```suggestion
        let ledger = LedgerWallet::new(account, wallet_config.network, None);
        // Verify that the user selected the correct application on the Ledger device
        match ledger
            .build_command(Instruction::GetPublicAlpha, vec![])
            .execute_with_transport(&hid)
        {
            Ok(result) => {
                // Verify the response
                ...
            }
            Err(e) => panic!("{}", e),
        }
        match ledger
            .build_command(Instruction::GetVersion, vec![])
            .execute_with_transport(&hid)
        {
            Ok(result) => {
                // Verify the response
                ...
            }
            Err(e) => panic!("{}", e),
        }
```

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/utils.rs
> +) -> Result<RistrettoSecretKey, AppSW> {
```suggestion
) -> Result<Zeroizing<RistrettoSecretKey>, AppSW> {
```

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/utils.rs
> +pub fn get_key_from_uniform_bytes(bytes: &[u8]) -> Result<RistrettoSecretKey, AppSW> {
```suggestion
pub fn get_key_from_uniform_bytes(bytes: &[u8]) -> Result<Zeroizing<RistrettoSecretKey>, AppSW> {
```

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/utils.rs
> +) -> Result<RistrettoSecretKey, AppSW> {
```suggestion
) -> Result<Zeroizing<RistrettoSecretKey>, AppSW> {
```

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_script_signature.rs
> +    let r_y: RistrettoSecretKey = get_key_from_canonical_bytes(&signer_ctx.payload[168..200])?;
Use  `Zeroizing` where ever possible for secret keys

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_script_offset.rs
> +pub fn handler_get_script_offset(
Use  `Zeroizing` where ever possible for secret keys

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
> +pub fn handler_get_metadata_signature(comm: &mut Comm) -> Result<(), AppSW> {
Use  `Zeroizing` where ever possible for secret keys

2024-05-15 13:37 UTC, hansieodendaal commented on applications/minotari_console_wallet/src/lib.rs
>      let wallet_type = prompt_wallet_type(boot_mode, &config.wallet, cli.non_interactive_mode);
We need to check the ledger app name and version here before we continue:, similar to when we create the wallet

2024-05-15 18:27 UTC, brianp commented on applications/minotari_ledger_wallet/wallet/Cargo.toml
> +tari_crypto = { version = "0.20.0", default-features = false, features = ["borsh"]}
`0.20.1` 👍🏻

2024-05-15 18:32 UTC, brianp commented on base_layer/key_manager/src/key_manager_service/service.rs
> +                let branch_key = km.get_private_key(*index)?;
I think they'll be a decent amount of churn that will occur in a lot of places. That's a tomorrow problem 😄

2024-05-15 18:34 UTC, brianp commented on applications/minotari_ledger_wallet/comms/src/ledger_wallet.rs
> +}
Created a ticker for this: https://github.com/orgs/tari-project/projects/16/views/1?pane=issue&itemId=63048443

2024-05-15 18:37 UTC, brianp commented on applications/minotari_console_wallet/src/init/mod.rs
> +                            let ledger = LedgerWallet::new(account, wallet_config.network, None);
Ticket opened here: https://github.com/orgs/tari-project/projects/16/views/1?pane=issue&itemId=63048614

2024-05-15 22:27 UTC, brianp commented
All changes made, or suggestions noted. The zeroizing caused me a bit of grief up front but it's all working now.

I've ensured issues are on the board for stuff like ensuring the correct ledger device is selected, checking app version etc. I knew we'd need to do these things but figured it might be best to start implementing in smaller more manageable PRs.

2024-05-16 06:15 UTC, SWvheerden reviewed
Missed one private key for zeroing

2024-05-16 06:15 UTC, SWvheerden commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
> +    let ephemeral_private_key = derive_from_bip32_key(account, ephemeral_private_nonce_index, KeyType::Nonce)?;
also needs a Zeroizing

2024-05-16 07:58 UTC, SWvheerden commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
> +    let ephemeral_private_key = derive_from_bip32_key(account, ephemeral_private_nonce_index, KeyType::Nonce)?;
wait no, my mistake, the function returns a zeroing key

2024-05-16 08:00 UTC, hansieodendaal approved these changes
utACK

2024-05-16 08:00 UTC, hansieodendaal commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
> +    )?);
Lets fix after merge, we do not need the double Zeroizing here

2024-05-16 08:01 UTC, SWvheerden approved these changes

2024-05-16 08:01 UTC, merged

2024-05-16 14:59 UTC, brianp commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
> +    )?);
Ahh yeah. That was a mistake. I'll tidy it in the next PR.

2024-05-16 15:01 UTC, brianp commented on applications/minotari_ledger_wallet/wallet/src/handlers/get_metadata_signature.rs
> +    let ephemeral_private_key = derive_from_bip32_key(account, ephemeral_private_nonce_index, KeyType::Nonce)?;
`derive_from_bip32_key` actually returns a zeroized key. It was in another location I double-zeroized the return value of this function. Which probably made this confusing.