feat: keep smt memory
tari-project/tari pull request #6265
Opened 2024-04-10 12:34 UTC by SWvheerden

Description
---
This only keeps only a single copy of the smt in memory

Motivation and Context
---
Writing and load the smt from disc every time is inefficient and take long, this keeps in in memory. 
Keeping a single copy in an `Arc<RwLock<>>` alles the node to keep a single copy and use it. 

How Has This Been Tested?
---
unit tests and manual.

2024-04-11 10:21 UTC, hansieodendaal requested changes
I am really impressed by the effect of this PR. I ran system-level testing to sync a 927,181 UTXO blockchain from scratch and archival block sync took 30 min, whereas horizon sync took 2 hours and 7 minutes (still something off with our implementation there, but not due to this PR).

**_Calculating the SMR for this test blockchain took in excess of 1 minute._**
I propose we add an SMT "caching/snapshot" function to the code to save the SMT to file when the base node exits together with the block hash for that height. Whenever the base node starts up it can read the SMT from file, verify that it is for the best block it has, and continue. Whenever it exits again it can create a new snapshot at the best block and delete the previous one. Whenever the SMT needs to be re-calculated during runtime, it could also make use of the snapshot as a starting point.

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
> +    fn calculate_tip_smt(&self) -> Result<OutputSmt, ChainStorageError> {
Please add a trace log that reports the time it takes to calculate the SMT, with some stat about the block height and SMT entry size etc.

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +    // lets rewind the smt back to tip again
Please explain a bit more in the comment, why this code is needed

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +                // some error happend, lets rewind the smt
```suggestion
                // some error happend, lets reset the smt to its starting state
```

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +    output_smt: &mut OutputSmt,
Please add a comment to explain that the SMT will be temporarily mutated in order to calculate the MMR roots, and that it needs to be reset to its original state before the function exits

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +        }
I count 3x places in the code where this pattern is employed, where the SMT needs to be recalculated if some underlying error happens, If this function (`calculate_tip_smt`) errors we cannot recover. 

Maybe at this point the SMT should be wiped, and we should have a wrapper function that checks to see if the SMT is empty and try to calculate it whenever we want to use it.

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +    }
Could this function not be turned into a helper function instead of taking `&self`, taking `smt: Arc<RwLock<OutputSmt>>` instead? Then it could be used in all other places in the code? I count 4x other places where this pattern is employed.

2024-04-11 10:21 UTC, hansieodendaal commented on base_layer/core/src/validation/block_body/block_body_full_validator.rs
> +        let mmr_roots = chain_storage::calculate_mmr_roots(backend, &self.consensus_manager, &block, &mut output_smt)?;
See previous comment about a helper function.

2024-04-11 11:53 UTC, SWvheerden commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +        }
if calculate_tip_smt fails, you entire db is stuffed, and you need to sync from scratch. Aka wipe the node. So I don't see the need to add a helper function to wipe it and only let it fail again. This replaces the SMT in memory.

2024-04-11 11:56 UTC, SWvheerden commented
If we want to save a min by caching the SMT, I created a ticket here: https://github.com/tari-project/tari/issues/6269
This PR is big enough as it is

2024-04-11 16:03 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +        }
It is better to have no SMT than to have one that is not in sync with the db. The calculate function could fail due to other reasons, not only due to bad lmdb data, for example the OS could be busy swapping memory to disk for a long time and impair other read operations.

2024-04-11 17:50 UTC, SWvheerden commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +        }
for that a restart of the node is better anyway

2024-04-12 07:03 UTC, hansieodendaal commented on base_layer/core/src/chain_storage/blockchain_database.rs
> +        }
Not resolved

2024-04-12 07:09 UTC, hansieodendaal approved these changes, later dismissed
ACK

Notes: 
- Some comments were not resolved
- CI must pass

2024-04-15 08:38 UTC, merged