fix: chat sending using wrong address
tari-project/tari pull request #6369
Opened 2024-06-04 14:44 UTC by SWvheerden

Description
---
Fixes chat using the wrong destination, and this getting the peer banned.

2024-06-04 15:00 UTC, brianp requested changes

2024-06-04 15:00 UTC, brianp commented on base_layer/contacts/src/contacts_service/service.rs
> +        let address = &message.receiver_address;
This doesn't seem correct to me.

The message is a received message, so we should still be the receiver address in this case. Meaning the confirmation needs to be sent to the `sender`

2024-06-04 17:14 UTC, brianp approved these changes

2024-06-24 07:05 UTC, SWvheerden commented
Dont think this will solve the issue, closing for now

2024-06-24 07:05 UTC, closed without merging