feat: commitment proofs
tari-project/tari pull request #6463
Opened 2024-08-12 00:23 UTC by AaronFeickert

Description
---
Adds commitment proofs, which prove knowledge of the opening of a commitment with an optional minimum value assertion.

Closes #6282.

Motivation and Context
---
This PR adds commitment proofs. These proofs show that the prover knows the opening of a given commitment, optionally shows that the commitment binds to at least a specified minimum value, and bind to an arbitrary message to mitigate replay attacks.

Notably, they do _not_ necessarily assert spend authority.

How Has This Been Tested?
---
This needs to be tested manually.

What process can a PR reviewer use to test or verify this change?
---
Test proof verification against valid values. Test proof verification against different commitments, minimum values, and messages.

2024-08-12 07:09 UTC, SWvheerden requested changes
This looks good as a proof of view access. Not necessarily proof of ownership. 
We need to move the proof generation to inside the key manager. The services should not work with the private keys. There is a lot of complexity there and it should be kept there. 

The ownership proof will only currently work for your own wallet as it searches only your own wallet for utxos.

2024-08-12 07:09 UTC, SWvheerden commented on applications/minotari_console_wallet/src/automation/commands.rs
> +                match output_service.get_unspent_outputs().await {
this will only allow you to verify your own commitments

2024-08-12 07:09 UTC, SWvheerden commented on applications/minotari_console_wallet/src/automation/commands.rs
> +                match output_service.get_unspent_outputs().await {
If you want to verify any output you probably need a new method that will get that from a base node

2024-08-12 07:09 UTC, SWvheerden commented on base_layer/wallet/src/output_manager_service/service.rs
> +    TKeyManagerInterface: SecretTransactionKeyManagerInterface,
```suggestion
    TKeyManagerInterface: TransactionKeyManagerInterface,
```
Dont include this trait. You are not suppose to expose the private keys here

2024-08-12 07:09 UTC, SWvheerden commented on base_layer/wallet/src/output_manager_service/service.rs
> +    async fn create_commitment_proof(
ship most of the work to the key manager. 
Its the only place where we should work with private keys.

2024-08-12 14:14 UTC, AaronFeickert commented
@SWvheerden thanks for the review! This was originally based on the design in #6240, but certainly looks like it needs to be changed to be properly useful.

2024-08-12 14:21 UTC, hansieodendaal reviewed
Looks nice, and I agree that we should keep the secret keys in the key manager. 

I initially thought that we should guard against someone just pulling an existing range proof from the blockchain and present it as an ownership proof, but then realized that the transcript is unique.

What is interesting, is that we could create this proof even if the actual output may have a revealed value proof.

2024-08-12 14:25 UTC, AaronFeickert commented
> then realized that the transcript is unique

Yep, this was very intentional. It's not possible to collide a commitment proof with a range proof. This is the case even in the "other direction", where an adversary tricks a user into including a malicious message in a commitment proof in an attempt to produce a valid range proof.

2025-03-04 08:10 UTC, SWvheerden commented
Going to close this for now, we have the issue still open for this, and this needs to be reworked to make it useful

2025-03-04 08:10 UTC, closed without merging